### ISSUE TITLE
"stable" release

### ISSUE THREAD

**Issue by Gummibeer** [nunomaduro/pest#25]
could you publish a stable release - I would be happy with a simple `0.1` one. But this would allow to install it without allowing real dev dependencies and don't trust your `dev-master` but have any kind of fixed version.

**Comment by nunomaduro** [comment]
@Gummibeer Would you like to help me out this project? 👍

**Comment by Gummibeer** [comment]
I would like to test it at first - atm I create a pretty small package which would be perfect to test it. But even for testing I don't want to require a branch - any kind of tag, even any `alpha`/`beta` would be great. :)

**Comment by nunomaduro** [comment]
Alright, I will do it this weekend.

**Comment by nunomaduro** [comment]
`v0.1.0` is out. Enjoy.
