### ISSUE TITLE
Conflict between packages/functions

### ISSUE THREAD

**Issue by avfigueredo** [nunomaduro/pest#29]
Hi, I am trying to install, but I getting this conflict between packages:

`PHP Fatal error:  Cannot redeclare once() (previously declared in vendor/spatie/once/src/functions.php:6) in /vendor/phpunit/phpunit/src/Framework/Assert/Functions.php on line 2529
`

Any idea of how I can resolve  this issue?

**Comment by nunomaduro** [comment]
I have no idea, sorry! Seems that a package you have installed already contains a global method we are using from phpunit.

**Comment by olivernybroe** [comment]
@avfigueredo You can try fiddling with excluding the file from the autoloader. However I cannot promise that stuff won't break my doing it.
