### ISSUE TITLE
Missing logo

### ISSUE THREAD

**Issue by nunomaduro** [nunomaduro/pest#4]

**Comment by caneco** [comment]
1, 2, 3… **LET'S GO!**

**Comment by nunomaduro** [comment]
@caneco I trust you blindly on this. Just PR directly into the art folder.

**Comment by olivernybroe** [comment]
Just let him commit directly to master with it. No need for approving the PR 😉

**Comment by caneco** [comment]
And I just know the perfect `git commit --message`

![image](https://user-images.githubusercontent.com/502041/62284628-dc1dd400-b44b-11e9-820a-df89d331804e.png)
